{% set name = "hspfbintoolbox" %}
{% set version = "9.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hspfbintoolbox-{{ version }}.tar.gz
  sha256: 4c528c3df14833b277452737971fa197cf5a4f883d0494cc3d9729af375b6c68

build:
  entry_points:
    - hspfbintoolbox = hspfbintoolbox.hspfbintoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - cltoolbox >1.1.0
    - dateparser
    - numpy >=1.20
    - numpy <2.0
    - pandas
    - pint
    - pint-pandas
    - python >={{ python_min }}
    - pydantic
    - scipy
    - tabulate

test:
  imports:
    - hspfbintoolbox
  commands:
    - pip check
    - hspfbintoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Reads Hydrological Simulation Program - FORTRAN binary output files.
  home: https://pypi.org/project/hspfbintoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
