{% set name = "hspfbintoolbox" %}
{% set version = "9.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hspfbintoolbox-{{ version }}.tar.gz
  sha256: b14a85da3d6bd6e9ad9536ef686a74a271199fd67397e81a148219211a6aa217

build:
  entry_points:
    - hspfbintoolbox = hspfbintoolbox.hspfbintoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - cltoolbox >1.1.0
    - dateparser
    - numpy >=1.20
    - numpy <2.0  # [py<=3.9]
    - pandas
    - pint
    - pint-pandas
    - python >=3.9
    - pydantic
    - scipy
    - tabulate

test:
  imports:
    - hspfbintoolbox
  commands:
    - pip check
    - hspfbintoolbox --help
  requires:
    - pip

about:
  summary: Reads Hydrological Simulation Program - FORTRAN binary output files.
  home: https://pypi.org/project/hspfbintoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
