{% set name = "hspfbintoolbox" %}
{% set version = "9.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hspfbintoolbox-{{ version }}.tar.gz
  sha256: 8ea9e9a16612be0115301e53829d9e2380a93afc0d14433ccf39acddca7ab24e

build:
  entry_points:
    - hspfbintoolbox = hspfbintoolbox.hspfbintoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - toolbox_utils >=5.0.0,<6.0.0
    - cltoolbox >1.1.0
    - pydantic
    - pandas

test:
  imports:
    - hspfbintoolbox
  commands:
    - pip check
    - hspfbintoolbox --help
  requires:
    - pip

about:
  summary: Reads Hydrological Simulation Program - FORTRAN binary output files.
  home: https://pypi.org/project/hspfbintoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
